name: Build, Test, and Prepare Release Candidate

on:
  pull_request:
    types:
      - labeled
      - reopened
      - synchronize

jobs:
  integration-tests:
    name: Java ${{ matrix.java }}, MySQL ${{ matrix.mysql }}
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'Extension Release Candidate :rocket:' )
    strategy:
      matrix:
        java: [8, 11, 16]
        mysql: [8]
    services:
      mysql:
        image: mysql:${{ matrix.mysql }}
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v2
    - name: Cache Local Maven Repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Test With Maven
      run: mvn clean verify --file pom.xml
